name: colibri
description: Colibri


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+13

environment:
  sdk: ">=2.8.0 <3.0.0"

flutter_localizations:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.10.0
  # for api calls
  dio: ^4.0.0 
  google_fonts: ^2.1.0 
  flutter_hooks: ^0.18.0 

  flutter_screenutil: ^5.0.0+2 
  rxdart: ^0.27.1 
  flutter_svg: ^0.22.0 
  flutter_bloc: ^7.1.0 

  freezed: 
  freezed_annotation:
  equatable: ^2.0.3 
  injectable: ^1.5.0
  get_it: ^7.2.0 
  flutter_webview_plugin: ^0.4.0
  another_flushbar: ^1.10.24
  font_awesome_flutter: ^9.1.0 
  cached_network_image: ^3.1.0
  image_picker: ^0.8.3+2 
  emoji_picker_flutter: ^1.0.7
  flutter_animated_dialog: ^2.0.1 
  giphy_picker: ^2.0.0
  flutter_secure_storage: ^4.2.1 
  intl: ^0.17.0
  carousel_slider: ^4.0.0 
  video_thumbnail: ^0.4.3
  video_player: 
  photo_view: ^0.12.0
  flutter_vlc_player: ^6.0.3 
  file_picker: ^4.0.0 
  flutter_cache_manager: ^3.1.2
  thumbnails: ^1.0.1
  path_provider: ^2.0.2 
  video_compress: ^3.1.0 
  flutter_easyloading: ^3.0.0 
  permission_handler: ^8.1.4+2 
  better_player: 0.0.70
  flutter_facebook_login: ^3.0.0 
  google_sign_in: ^5.0.7 
  infinite_scroll_pagination: ^3.1.0 
  auto_size_text: ^2.1.0
  faker: ^2.0.0 
  native_device_orientation: ^1.0.0
  mime: ^1.0.0
  velocity_x: ^3.3.0
  timelines: ^0.1.0 
  url_launcher: ^6.0.9 
  animations: ^2.0.1 
  html_unescape: ^2.0.0 
  flutter_linkify: ^5.0.2 
  share: ^2.0.4
  webview_flutter: ^2.0.12 
  shared_preferences: 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3 
  material_floating_search_bar: ^0.3.4
  pull_to_refresh: ^2.0.0 
  flutter_local_notifications: ^8.1.1+1
  image_cropper: ^1.4.1 
  expandable_page_view: ^1.0.6 
  flutter_image_compress: ^1.1.0 
  #Discontinued
  file_utils: ^1.0.1
  keyboard_actions: ^3.4.3
  firebase_messaging: ^10.0.6
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  smart_select: ^4.3.2
  remove_emoji: ^0.0.6 
  page_indicator: ^0.4.1
  page_view_indicators: ^2.0.0 
  modal_bottom_sheet: ^2.0.0 
  easy_localization: ^3.0.0  
  html: ^0.15.0
  keyboard_visibility: ^0.5.6 
  simple_url_preview: ^3.0.1 
  youtube_player_flutter: ^8.0.0 
  
  awsome_video_player: ^1.0.8+1

  syncfusion_flutter_charts: ^19.3.45+1
  syncfusion_flutter_sliders: ^19.3.45


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 
  build_runner:
  copy_with_extension_gen: 
  flutter_keyboard_visibility: 
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:
  generate: true
  uses-material-design: true

  
  assets:
    - images/
    - images/png_image/
    - assets/translations/


  fonts:
#   
    - family: Campton
      fonts:
        - asset: fonts/Campton-Light.ttf
          weight: 200
        - asset: fonts/Campton-Medium.ttf
          weight: 400
        - asset: fonts/Campton-Bold.ttf
          weight: 600
    - family: CeraPro
      fonts:
        - asset: fonts/CeraPro-Regular.ttf
          weight: 200
        - asset: fonts/CeraPro-Medium.ttf
          weight: 400
        - asset: fonts/CeraPro-Bold.ttf
          weight: 600

